/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service is alive */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status?: "ok";
                            version?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new organisation and admin user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                /** @description Email already registered */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange credentials for access + refresh tokens
         * @description Returns 401 with a generic message on any auth failure. Never
         *     reveals whether the user exists.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate refresh token, return new access token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        refreshToken: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The authenticated user's profile */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all organisations (public — for register dropdown) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            name: string;
                        }[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users in the caller's organisation */
        get: {
            parameters: {
                query?: {
                    status?: components["schemas"]["UserStatus"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrgUser"][];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a user's role, active flag, or status */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        role?: components["schemas"]["UserRole"];
                        isActive?: boolean;
                        status?: components["schemas"]["UserStatus"];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrgUser"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/users/{userId}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve a pending user (sets status to active) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrgUser"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{userId}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject a pending user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrgUser"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all organisations (super_admin only) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminOrg"][];
                    };
                };
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/organizations/{orgId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update an organisation's name or timezone (super_admin only) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orgId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name?: string;
                        timezone?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminOrg"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/admin/organizations/{orgId}/users": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orgId: string;
            };
            cookie?: never;
        };
        /** List all users in a specific organisation (super_admin only) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orgId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminUser"][];
                    };
                };
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all users across all organisations (super_admin only) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminUser"][];
                    };
                };
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update any user across all orgs (super_admin only) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        role?: components["schemas"]["UserRole"];
                        isActive?: boolean;
                        status?: components["schemas"]["UserStatus"];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminUser"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List registered log sources */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["PageParam"];
                    pageSize?: components["parameters"]["PageSizeParam"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeviceList"];
                    };
                };
            };
        };
        put?: never;
        /** Register a new log source */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DeviceCreate"];
                };
            };
            responses: {
                /**
                 * @description Returns the device record plus the one-time shared secret used
                 *     by the device to authenticate to the ingestor. The secret is
                 *     shown only once and never returned by GET.
                 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Device"] & {
                            sharedSecret: string;
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/{deviceId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: components["parameters"]["DeviceIdParam"];
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    deviceId: components["parameters"]["DeviceIdParam"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Device"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    deviceId: components["parameters"]["DeviceIdParam"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    deviceId: components["parameters"]["DeviceIdParam"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DeviceUpdate"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Device"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List incidents with filters */
        get: {
            parameters: {
                query?: {
                    severity?: components["schemas"]["Severity"];
                    status?: components["schemas"]["IncidentStatus"];
                    deviceId?: string;
                    from?: string;
                    to?: string;
                    page?: components["parameters"]["PageParam"];
                    pageSize?: components["parameters"]["PageSizeParam"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IncidentList"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/incidents/{incidentId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incidentId: components["parameters"]["IncidentIdParam"];
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    incidentId: components["parameters"]["IncidentIdParam"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Incident"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update incident status (acknowledge, confirm, false positive) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    incidentId: components["parameters"]["IncidentIdParam"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        status: components["schemas"]["IncidentStatus"];
                        note?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Incident"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/incidents/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * WebSocket feed of new and updated incidents
         * @description Upgrades the connection to a WebSocket. The client receives
         *     `IncidentEvent` messages until disconnected. Falls back gracefully
         *     to 30-second polling on `/incidents` when the WebSocket fails.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Switching Protocols (WebSocket) */
                101: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/kpis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** KPI tile data for the dashboard */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DashboardKpis"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/threat-map": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Geo-IP arc data for the threat map */
        get: {
            parameters: {
                query?: {
                    hours?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            center: components["schemas"]["GeoPoint"];
                            arcs: components["schemas"]["ThreatArc"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alert-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AlertRule"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AlertRuleCreate"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AlertRule"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alert-rules/{ruleId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ruleId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    ruleId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    ruleId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AlertRuleUpdate"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AlertRule"];
                    };
                };
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @example invalid_credentials */
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
        /**
         * @description Exactly one of organizationName (create new org) or organizationId (join existing) must be set.
         *     Creating a new org → role is forced to admin, status active.
         *     Joining an existing org → chosen role, status pending (awaiting approval).
         */
        RegisterRequest: {
            organizationName?: string | null;
            /** Format: uuid */
            organizationId?: string | null;
            /** Format: email */
            email: string;
            password: string;
            role?: components["schemas"]["UserRole"];
            /** @example Australia/Brisbane */
            timezone?: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        AuthResponse: {
            accessToken?: string;
            refreshToken?: string;
            /**
             * @description Seconds until access token expires
             * @example 900
             */
            expiresIn?: number;
            user?: components["schemas"]["User"];
            /** @default false */
            mfaRequired: boolean;
            mfaToken?: string | null;
        };
        /** @enum {string} */
        UserRole: "super_admin" | "admin" | "senior_analyst" | "analyst" | "threat_hunter" | "forensic_investigator" | "auditor" | "developer";
        /** @enum {string} */
        UserStatus: "pending" | "active" | "rejected";
        User: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organizationId: string;
            /** Format: email */
            email: string;
            role: components["schemas"]["UserRole"];
            status: components["schemas"]["UserStatus"];
            mfaEnrolled: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        OrgUser: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            role: components["schemas"]["UserRole"];
            isActive: boolean;
            status: components["schemas"]["UserStatus"];
            mfaEnrolled: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        AdminOrg: {
            /** Format: uuid */
            id: string;
            name: string;
            timezone: string;
            userCount: number;
            /** Format: date-time */
            createdAt: string;
        };
        AdminUser: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organizationId: string;
            organizationName: string;
            /** Format: email */
            email: string;
            role: components["schemas"]["UserRole"];
            isActive: boolean;
            status: components["schemas"]["UserStatus"];
            mfaEnrolled: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        /** @enum {string} */
        DeviceVendor: "pfsense" | "opnsense" | "mikrotik" | "fortigate" | "generic_syslog";
        /** @enum {string} */
        DeviceProtocol: "syslog" | "netflow" | "pcap";
        Device: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organizationId: string;
            name: string;
            vendor: components["schemas"]["DeviceVendor"];
            protocol: components["schemas"]["DeviceProtocol"];
            /** Format: ipv4 */
            publicIp: string;
            location?: components["schemas"]["GeoPoint"];
            /** Format: date-time */
            lastSeenAt?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        DeviceCreate: {
            name: string;
            vendor: components["schemas"]["DeviceVendor"];
            protocol: components["schemas"]["DeviceProtocol"];
            /** Format: ipv4 */
            publicIp: string;
            location?: components["schemas"]["GeoPoint"];
        };
        DeviceUpdate: {
            name?: string;
            location?: components["schemas"]["GeoPoint"];
        };
        DeviceList: {
            items: components["schemas"]["Device"][];
            page: number;
            pageSize: number;
            total: number;
        };
        /** @enum {string} */
        Severity: "info" | "low" | "medium" | "high" | "critical";
        /** @enum {string} */
        IncidentStatus: "open" | "acknowledged" | "confirmed" | "false_positive";
        /** @enum {string} */
        AttackLabel: "port_scan" | "ddos" | "brute_force" | "c2_beaconing" | "data_exfil" | "lateral_movement" | "unknown_anomaly";
        Incident: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organizationId: string;
            /** Format: uuid */
            deviceId: string;
            /** Format: date-time */
            detectedAt: string;
            severity: components["schemas"]["Severity"];
            status: components["schemas"]["IncidentStatus"];
            attackLabel: components["schemas"]["AttackLabel"];
            /** @example T1046 */
            mitreTechnique: string;
            sourceIp: string;
            destinationIp: string;
            /** Format: float */
            anomalyScore: number;
            /** @description Plain-English summary, LLM-generated, with template fallback. */
            narrative?: string | null;
            topFeatures?: {
                name: string;
                value: number;
            }[];
        };
        IncidentList: {
            items: components["schemas"]["Incident"][];
            page: number;
            pageSize: number;
            total: number;
        };
        IncidentEvent: {
            /** @enum {string} */
            type: "created" | "updated";
            incident: components["schemas"]["Incident"];
        };
        DashboardKpis: {
            eventsPerSecond: number;
            openIncidentsBySeverity: {
                info: number;
                low: number;
                medium: number;
                high: number;
                critical: number;
            };
            topInternalTalkers: {
                ip: string;
                /** Format: int64 */
                bytes: number;
            }[];
            topExternalDestinations: {
                ip: string;
                country: string;
                /** Format: int64 */
                bytes: number;
            }[];
        };
        GeoPoint: {
            lat: number;
            lng: number;
        };
        ThreatArc: {
            from: components["schemas"]["GeoPoint"];
            to: components["schemas"]["GeoPoint"];
            count: number;
            severity: components["schemas"]["Severity"];
            sourceCountry?: string;
        };
        /** @enum {string} */
        AlertChannel: "email" | "sms" | "push";
        AlertRule: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organizationId: string;
            name: string;
            minSeverity: components["schemas"]["Severity"];
            mitreFilter?: string[];
            channel: components["schemas"]["AlertChannel"];
            /** Format: uuid */
            targetUserId?: string | null;
            enabled: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        AlertRuleCreate: {
            name: string;
            minSeverity: components["schemas"]["Severity"];
            mitreFilter?: string[];
            channel: components["schemas"]["AlertChannel"];
            /** Format: uuid */
            targetUserId?: string;
            /** @default true */
            enabled: boolean;
        };
        AlertRuleUpdate: {
            name?: string;
            minSeverity?: components["schemas"]["Severity"];
            mitreFilter?: string[];
            channel?: components["schemas"]["AlertChannel"];
            /** Format: uuid */
            targetUserId?: string;
            enabled?: boolean;
        };
    };
    responses: {
        /** @description Validation failure */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Invalid or missing credentials */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Insufficient permissions */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        PageParam: number;
        PageSizeParam: number;
        DeviceIdParam: string;
        IncidentIdParam: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
